name: Slack Notifier
on:
  schedule:
    - cron: "30 23 * * 0-4"  # UTC 23:30 → 한국시간 08:30 (월~금)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install streamlit pandas sqlalchemy pymysql requests pytz
      - name: Send Slack Notification
        run: python auto_slack_notifier.py
        env:
          STREAMLIT_SECRETS: ${{ secrets.STREAMLIT_SECRETS }}
